version: "3"
services:
  database-mysql:
    image: mysql:8
    container_name: ""
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:
    ports:
      - "3306:3306"
    volumes:
      # - ./volume:/var/lib/mysql -> Set volume at your prefernece
  backend-node:
    container_name: ""
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:3000"
    depends_on:
      - database-mysql
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./app/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
